
jobs:

- job: "LinuxPythonDebug"
  displayName: "Ubuntu build - python make - debug"
  pool:
    vmImage: "Ubuntu-16.04"
  steps:
    - script: python scripts/mk_make.py -d
    - script: |
        cd build
        make
    - script: git clone https://github.com/z3prover/z3test z3test
    - script: python z3test/scripts/test_benchmarks.py build/z3.exe z3test/regressions/smt2
    - script: |
        cd build
        make cpp_example
        cpp_example.exe
        make java_example
        make dotnet_example
        make test-z3
        test-z3 -a


- job: "LinuxCMake"
  displayName: "Ubuntu build - cmake"
  pool:
    vmImage: "Ubuntu-16.04"
  steps:
    - task: DotNetCoreInstaller@0
      displayName: 'Use .NET Core sdk 2.1'
      inputs:
        version: 2.1.300
    # TBD add steps for building and testing
    # debug/release/asan/ubsan/

- job: "Windows2017"
  displayName: "Windows 2017 build"
  pool:
    vmImage: "vs2017-win2016"
  steps:
    - script: scripts\vsts-vs2017.cmd x64



# TBD add job for Mac build/test 








