pool:
  vmImage: "vs2017-win2016"

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.1'
  inputs:
    version: 2.1.300

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'z3.snk'

- script: scripts\vsts-vs2017.cmd x64

- script: scripts\vsts-vs2013.cmd






