
jobs:

- job: "LinuxPython"
  displayName: "Ubuntu build - python make"
  pool:
    vmImage: "Ubuntu-16.04"
  steps:
    - task: DotNetCoreInstaller@0
      displayName: 'Use .NET Core sdk 2.1'
      inputs:
        version: 2.1.300
    # TBD add steps for building and testing

- job: "LinuxCMake"
  displayName: "Ubuntu build - cmake"
  pool:
    vmImage: "Ubuntu-16.04"
  steps:
    - task: DotNetCoreInstaller@0
      displayName: 'Use .NET Core sdk 2.1'
      inputs:
        version: 2.1.300
    # TBD add steps for building and testing
    # debug/release/asan/ubsan/

- job: "Windows2017"
  displayName: "Windows 2017 build"
  pool:
    vmImage: "vs2017-win2016"
  steps:
    - task: DotNetCoreInstaller@0
      displayName: 'Use .NET Core sdk 2.1'
      inputs:
        version: 2.1.300
    - script: scripts\vsts-vs2017.cmd x64



# TBD add job for Mac build/test 








