jobs:

- job: "Mac"
  displayName: "Mac Build"
  pool:
    vmImage: "macOS-10.14"
  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'z3.snk'
  - script: python scripts/mk_unix_dist.py --dotnet-key=$(Agent.TempDirectory)/z3.snk
  - script: cp dist/*.zip $(Build.ArtifactStagingDirectory)/.
  - task: GitHubRelease@0
    inputs:
      gitHubConnection: Z3GitHub
      repositoryName: 'Z3Prover/z3'
      action: 'edit'
      target: '$(Build.SourceVersion)'
      tagSource: 'manual'
      tag: 'Nightly'
      title: 'Nightly'
      releaseNotesSource: 'input'
      releaseNotes: 'nightly build'
      assetUploadMode: 'replace'
      isDraft: false
      isPreRelease: true

- job: "Ubuntu"
  displayName: "Ubuntu build"
  pool:
    vmImage: "ubuntu-16.04"
  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'z3.snk'
  - script: python scripts/mk_unix_dist.py --dotnet-key=$(Agent.TempDirectory)/z3.snk
  - script: cp dist/*.zip $(Build.ArtifactStagingDirectory)/.
  - task: GitHubRelease@0
    inputs:
      gitHubConnection: Z3GitHub
      repositoryName: 'Z3Prover/z3'
      action: 'edit'
      target: '$(Build.SourceVersion)'
      tagSource: 'manual'
      tag: 'Nightly'
      title: 'Nightly'
      releaseNotesSource: 'input'
      releaseNotes: 'nightly build'
      assetUploadMode: 'replace'
      isDraft: false
      isPreRelease: true

- job: "Windows"
  displayName: "Windows build"
  pool:
    vmImage: "vs2017-win2016"
  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'z3.snk'
  - script: scripts\mk_win_dist.cmd
  - script: xcopy dist\*.zip $(Build.ArtifactStagingDirectory)\* /y
  - task: GitHubRelease@0
    inputs:
      gitHubConnection: Z3GitHub
      repositoryName: 'Z3Prover/z3'
      action: 'edit'
      target: '$(Build.SourceVersion)'
      tagSource: 'manual'
      tag: 'Nightly'
      title: 'Nightly'
      releaseNotesSource: 'input'
      releaseNotes: 'nightly build'
      assetUploadMode: 'replace'
      isDraft: false
      isPreRelease: true





