name: WASM Build

on:
  push:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure CMake and build
      run:  |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_SYSTEM_NAME=WASM -DCMAKE_SYSTEM_VERSION=21 
        make -j $(nproc)
        tar -cvf z3-build-wasm.tar *.jar *.so
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-wasm
        path: build/z3-build-wasm.tar
